### ISSUE TITLE
No way to write a tab (or not documented)

### ISSUE THREAD

**Issue by soweliniko** [VikOlliver/Quirkey#1]
The keymap seems to be missing a way to write a tab. This is very useful (for example, tab complete). It may exist but be undocumented.

**Comment by VikOlliver** [comment]
It's in the Command map. Do Command-T : Command key, first finger, ring finger. Works with shift and alt to do all the usual weird tab stuff as well.

Vik :v)

**Comment by soweliniko** [comment]
Ah thanks. Sorry, reading issue on my part.
